In [1]:
# 完成Numpy的数组和原生python的性能对比
import random
import time
import numpy as np

In [2]:
num0 = []
for i in range(10000000):
    num0.append(random.random())
print("完成")

完成


In [3]:
num1 = np.array(num0)
print("完成")

完成


In [4]:
list1 = time.time()
sum1 = sum(num0)
list2 = time.time()

list3 = time.time()
sum2 = np.sum(num1)
list4 = time.time()
print(list2 - list1, list4 - list3)

0.09848618507385254 0.016523361206054688


In [5]:
list1 = np.array([1,2,3])
print(list1)
print(type(list1))

[1 2 3]
<class 'numpy.ndarray'>


In [6]:
print(type(range(100)))
list2 = np.array(range(100))
print(list2)
print(type(list2))

<class 'range'>
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
<class 'numpy.ndarray'>


In [9]:
list3 = np.arange(0,100,4)
print(list3)
print(type(list3))

[ 0  4  8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68 72 76 80 84 88 92
 96]
<class 'numpy.ndarray'>


In [10]:
list4= [[1,2,3],[4,5,6],[7,8,9]]
twoArray = np.array(list4)
print(type(twoArray))
print(twoArray)
print(list4)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [11]:
twoArray.tolist()

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]