In [2]:
# 掌握numpy的数据类型，练习数组和数的运算，数组和数组的运算，理解数组的轴
import numpy as np
import random

In [8]:
# 创建数组
num = np.array([1,2,3,4,12],dtype=np.int8)#创建数组
print(num.itemsize)
print(num.dtype)

1
int8


In [9]:
num[4]= num[4] + 1

In [12]:
num[4]

np.int8(13)

In [13]:
num1 = num.astype(np.int64)#改变数据类型
print(num1.dtype)
print(num1.itemsize)

int64
8


In [14]:
# 练习数组和数的运算
num1 = np.arange(35).reshape(7,5)#创建数组
print(num1)
num2 = num1.tolist()
print(num1+2)
print(num1*2)
print(num1/2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]]
[[ 2  3  4  5  6]
 [ 7  8  9 10 11]
 [12 13 14 15 16]
 [17 18 19 20 21]
 [22 23 24 25 26]
 [27 28 29 30 31]
 [32 33 34 35 36]]
[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]
 [50 52 54 56 58]
 [60 62 64 66 68]]
[[ 0.   0.5  1.   1.5  2. ]
 [ 2.5  3.   3.5  4.   4.5]
 [ 5.   5.5  6.   6.5  7. ]
 [ 7.5  8.   8.5  9.   9.5]
 [10.  10.5 11.  11.5 12. ]
 [12.5 13.  13.5 14.  14.5]
 [15.  15.5 16.  16.5 17. ]]


In [16]:
#加减乘除
num1 = np.arange(25).reshape(5,5)#创建数组
num2 = np.arange(100,125).reshape(5,5)#创建数组
print(num1)
print(num2)
print(num1+num2)#数组的加减乘除
print(num1-num2)#数组的加减乘除
print(num1*num2)#数组的加减乘除
print(num1/num2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[100 101 102 103 104]
 [105 106 107 108 109]
 [110 111 112 113 114]
 [115 116 117 118 119]
 [120 121 122 123 124]]
[[100 102 104 106 108]
 [110 112 114 116 118]
 [120 122 124 126 128]
 [130 132 134 136 138]
 [140 142 144 146 148]]
[[-100 -100 -100 -100 -100]
 [-100 -100 -100 -100 -100]
 [-100 -100 -100 -100 -100]
 [-100 -100 -100 -100 -100]
 [-100 -100 -100 -100 -100]]
[[   0  101  204  309  416]
 [ 525  636  749  864  981]
 [1100 1221 1344 1469 1596]
 [1725 1856 1989 2124 2261]
 [2400 2541 2684 2829 2976]]
[[0.         0.00990099 0.01960784 0.02912621 0.03846154]
 [0.04761905 0.05660377 0.06542056 0.07407407 0.08256881]
 [0.09090909 0.0990991  0.10714286 0.11504425 0.12280702]
 [0.13043478 0.13793103 0.14529915 0.15254237 0.15966387]
 [0.16666667 0.17355372 0.18032787 0.18699187 0.19354839]]


In [18]:
num1 = np.arange(25).reshape(5,5)
num2 = np.arange(100,125).reshape(5,5)
print(num2.shape)
print(num1)
print(num2)
num2 - num1

(5, 5)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[100 101 102 103 104]
 [105 106 107 108 109]
 [110 111 112 113 114]
 [115 116 117 118 119]
 [120 121 122 123 124]]


array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [19]:
(num2 - num1).shape

(5, 5)

In [20]:
num1 = np.arange(27).reshape(3,3,3)
num2 = np.arange(100,127).reshape(3,3,3)
num1 - num2

array([[[-100, -100, -100],
        [-100, -100, -100],
        [-100, -100, -100]],

       [[-100, -100, -100],
        [-100, -100, -100],
        [-100, -100, -100]],

       [[-100, -100, -100],
        [-100, -100, -100],
        [-100, -100, -100]]])

In [23]:
# 理解数组的轴
num = np.array([[1,2,3],[4,5,6]])
print(num)
print(np.sum(num,axis=0))
print(np.sum(num,axis=1))
print(np.sum(num))

[[1 2 3]
 [4 5 6]]
[5 7 9]
[ 6 15]
21


In [25]:
num1 = np.arange(27).reshape(3,3,3)
num2 = np.sum(num1,axis=0)
print(num2.shape)
num3 = np.sum(num1,axis=1)
print(num3.shape)
num4 = np.sum(num1,axis=2)
print(num4.shape)

(3, 3)
(3, 3)
(3, 3)
