In [1]:
# 使用数组的索引和切片，掌握数组数值修改
import numpy as np

In [9]:
num = np.arange(20)
print(num[1],num)# 打印数组
print(num[2:18:2])# 打印索引为2到18的偶数

1 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 2  4  6  8 10 12 14 16]


In [11]:
num1 = np.arange(30).reshape(5,6)
print(num1)# 打印数组
print(num1[3])# 打印第三行
print(num1[2:])# 打印第三行到最后一行
print(num1[2:4,:])# 打印第三行到第四行的所有列
print(num1[[1,3,4]])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
[18 19 20 21 22 23]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 6  7  8  9 10 11]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [13]:
print(num1[:,1])# 所有行，第一列
print(num1[:,1:])# 所有行，第一列到最后一列
print(num1[:,[0,3,4]])# 所有行，第一列，第四列，第五列
num1[1:3,1:4]

[ 1  7 13 19 25]
[[ 1  2  3  4  5]
 [ 7  8  9 10 11]
 [13 14 15 16 17]
 [19 20 21 22 23]
 [25 26 27 28 29]]
[[ 0  3  4]
 [ 6  9 10]
 [12 15 16]
 [18 21 22]
 [24 27 28]]


array([[ 7,  8,  9],
       [13, 14, 15]])

In [14]:
# 掌握数组数值修改
num = np.arange(30).reshape(5,6)# 创建数组
print(num)
print(id(num))
num[1,:] = 0# 把第二行的所有值改为0
num[:,1] = 0# 把第一列的所有值改为0
num[1:3,:] = 0# 把第二行到第三行的所有值改为0
num[1:3,2:5] = 0# 把第二行到第三行的第三列到第五列的值改为0
num[[0,1],[1,3]] = 0 # 把第一行的第二列和第四列的值改为0

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
2244044132816
