In [1]:
# Numpy的ndarray的一维，二维的操作，常用属性，形状调整，与python list的互相转换
# 一维
import numpy as np
list1 = [1,2,3,4,5,6,7,8,9]
print(list1)
print(type(list1))

[1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>


In [2]:
# 二维
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(type(arr))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [3]:
# 常用属性
list2 = [[1,2,3],[4,5,6],[7,8,9]]
twoArray = np.array(list2)
print(twoArray.ndim)
print(twoArray.shape)
print(twoArray.size)
print(twoArray.dtype)

2
(3, 3)
9
int64


In [6]:
# 形状调整
num1 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(num1)
num2 = num1
print(id(num1))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2374977653232


In [7]:
num1.shape = (3,4)
print(id(num1))
print(id(num2))
print(num1)

2374977653232
2374977653232
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [8]:
num2 = num1.reshape((3,4))
print(num2)
print(id(num1))
print(id(num2))
num2

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2374977653232
2374978466320


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
# 形状调整
num3 = num1.reshape((12,),order='C')
num4 = num1.flatten()
print(num3)
print(num4)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [14]:
num5 = num3.reshape(4,3)
num5

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [15]:
# 与python list的互相转换
# list转array
num = np.array([1,2,3,4,5,6,7,8,9])
print(type(num))
list_num = num.tolist()
print(list_num)
print(type(list_num))

<class 'numpy.ndarray'>
[1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>
