In [1]:
# 练习series和df的索引操作,函数应用
import pandas as pd
num = pd.Series(range(10,30))#创建一个序列生成10-29的数字
print(num)

0     10
1     11
2     12
3     13
4     14
5     15
6     16
7     17
8     18
9     19
10    20
11    21
12    22
13    23
14    24
15    25
16    26
17    27
18    28
19    29
dtype: int64


In [2]:
print(num.values)#查看序列的值和类型
print(type(num.values))
print(num.index)#查看序列的索引
num.dtype#查看序列的数据类型

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
<class 'numpy.ndarray'>
RangeIndex(start=0, stop=20, step=1)


dtype('int64')

In [4]:
print(num[0])#查看序列的第0个元素
num[7]#查看序列的第7个元素

10


np.int64(17)

In [5]:
print(num*2)#序列的每个元素乘以2
print(num > 17)#序列的每个元素与17比较

0     20
1     22
2     24
3     26
4     28
5     30
6     32
7     34
8     36
9     38
10    40
11    42
12    44
13    46
14    48
15    50
16    52
17    54
18    56
19    58
dtype: int64
0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8      True
9      True
10     True
11     True
12     True
13     True
14     True
15     True
16     True
17     True
18     True
19     True
dtype: bool


In [7]:
num = {2000:14.5,2001:15.5,2002:16.5}#创建一个字典
data = pd.Series(num)#将字典转换为序列
print(data)
print(data.index)#查看序列的索引
print(data[2002])#查看序列的第2002个元素
num.values#查看序列的值

2000    14.5
2001    15.5
2002    16.5
dtype: float64
Index([2000, 2001, 2002], dtype='int64')
16.5


<function dict.values>

In [8]:
print(data.name)#查看序列的名称
print(data.index.name)#查看序列的索引名称
data.name = 'population'#给序列命名
data.index.name = 'year'#给序列的索引命名
print(data.head())#查看序列的前5个元素

None
None
year
2000    14.5
2001    15.5
2002    16.5
Name: population, dtype: float64


In [9]:
import numpy as np
num = pd.DataFrame(np.arange(15).reshape(3,5))#创建一个3行5列的DataFrame
print(num)

    0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14


In [11]:
data = np.random.randn(10,5)#创建一个10行5列的随机数DataFrame
print(data)
data_list = pd.DataFrame(data)#将随机数转换为DataFrame
print(data_list.head())#查看DataFrame的前5行

[[ 0.31633401 -0.88667532  2.53595618  1.58108028  1.05935102]
 [ 0.23493809 -2.14259188 -0.49347555  1.08322585 -0.71097012]
 [ 1.30455509 -0.84259469 -0.37880974 -0.31854748  0.61127389]
 [ 0.36306514  0.11401487  0.75793465  0.08944562  0.68431558]
 [ 0.21356966 -1.85385518 -1.32046709 -1.89119829 -2.5131772 ]
 [ 0.72596016 -0.13168124 -1.13618686 -0.84185243  0.44944333]
 [-1.36689432 -0.12366957  1.05103072 -0.72544303 -1.06876278]
 [ 0.86186116  0.84424709  0.05880929 -0.37677644  1.04742429]
 [-1.81552657  0.22973303 -0.16796522  0.75136919  1.38021485]
 [-0.7291807   0.23826798  0.24675477  1.66953478 -0.83594128]]
          0         1         2         3         4
0  0.316334 -0.886675  2.535956  1.581080  1.059351
1  0.234938 -2.142592 -0.493476  1.083226 -0.710970
2  1.304555 -0.842595 -0.378810 -0.318547  0.611274
3  0.363065  0.114015  0.757935  0.089446  0.684316
4  0.213570 -1.853855 -1.320467 -1.891198 -2.513177


In [12]:
num.loc[2]#查看DataFrame的第2行

0    10
1    11
2    12
3    13
4    14
Name: 2, dtype: int64

In [13]:
dict = [{"name":"zhangsan","age":20,"tel":123456},
        {"name":"lisi","age":30,"tel":123456},
        {"name":"wangwu","age":40,"tel":123456}]#创建一个字典列表
dict1 = pd.DataFrame(dict)#将字典列表转换为DataFrame
print(dict1)#查看DataFrame
print(type(dict1.values))#查看DataFrame的值

       name  age     tel
0  zhangsan   20  123456
1      lisi   30  123456
2    wangwu   40  123456
<class 'numpy.ndarray'>


In [14]:
dict_data = {'A':1,
             'B': pd.Timestamp('20190926'),
             'C': pd.Series(1, index=list(range(4)),dtype='float32'),
             'D': np.array([1,2,3,4],dtype='int32'),
             'E': ["Python","Java","C++","C"],
             'F': 'wangdao' }#创建一个字典
data_dict = pd.DataFrame(dict_data)#将字典转换为DataFramepr
print(data_dict)#查看DataFrame

   A          B    C  D       E        F
0  1 2019-09-26  1.0  1  Python  wangdao
1  1 2019-09-26  1.0  2    Java  wangdao
2  1 2019-09-26  1.0  3     C++  wangdao
3  1 2019-09-26  1.0  4       C  wangdao


In [15]:
print(data_dict.index)#查看DataFrame的索引
print(data_dict.columns)#查看DataFrame的列名
data_dict.dtypes#查看DataFrame的数据类型


Index([0, 1, 2, 3], dtype='int64')
Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')


A            int64
B    datetime64[s]
C          float32
D            int32
E           object
F           object
dtype: object

In [16]:
print(data_dict)#查看DataFrame
print(type(data_dict))#查看DataFrame的类型
print(data_dict['C'])#查看DataFrame的C列]
print(type(data_dict['C']))#查看C列的类型

   A          B    C  D       E        F
0  1 2019-09-26  1.0  1  Python  wangdao
1  1 2019-09-26  1.0  2    Java  wangdao
2  1 2019-09-26  1.0  3     C++  wangdao
3  1 2019-09-26  1.0  4       C  wangdao
<class 'pandas.core.frame.DataFrame'>
0    1.0
1    1.0
2    1.0
3    1.0
Name: C, dtype: float32
<class 'pandas.core.series.Series'>


In [17]:
del(data_dict['C'])#删除DataFrame的C列
print(data_dict.head())#查看DataFrame的前5行

   A          B  D       E        F
0  1 2019-09-26  1  Python  wangdao
1  1 2019-09-26  2    Java  wangdao
2  1 2019-09-26  3     C++  wangdao
3  1 2019-09-26  4       C  wangdao
