In [1]:
# 完成nan和inf的使用，掌握数组中nan值去除，替换为对应列的平均值
import numpy as np
num1 = np.nan#nan是浮点数，表示缺失值
num2 = np.inf#无穷大，表示无穷大的数
print(num1,type(num1))
print(num2,type(num2))

nan <class 'float'>
inf <class 'float'>


In [2]:
t = np.arange(24,dtype=float).reshape(4,6)#生成一个4行6列的数组
t[2,4] = np.nan#将第3行第5列设置为nan
print(np.count_nonzero(t))#统计非零元素个数
print(np.count_nonzero(t != t))#统计nan元素个数

23
1


In [3]:
t [np.isnan(t)] = 0#将所有nan替换为0
print(t)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15.  0. 17.]
 [18. 19. 20. 21. 22. 23.]]


In [4]:
t = np.arange((28)).reshape(4,7).astype('float')#生成一个4行7列的数组
t[2,2:] = np.nan#将第3行第3列到第6列设置为nan
print(t)

[[ 0.  1.  2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11. 12. 13.]
 [14. 15. nan nan nan nan nan]
 [21. 22. 23. 24. 25. 26. 27.]]


In [5]:
for i in range(t.shape[1]):#遍历每一列
    temp = t[:,i]#取出当前列
    nan_num = np.count_nonzero((temp != temp))#统计当前列的nan个数
    if nan_num != 0:
        temp_not_nan = temp[temp == temp]
        temp[np.isnan(temp)] = np.mean(temp_not_nan)#将当前列的nan替换为非零元素的平均值
print(t)

[[ 0.          1.          2.          3.          4.          5.
   6.        ]
 [ 7.          8.          9.         10.         11.         12.
  13.        ]
 [14.         15.         11.33333333 12.33333333 13.33333333 14.33333333
  15.33333333]
 [21.         22.         23.         24.         25.         26.
  27.        ]]
