In [2]:
# np二维数组转置练习，轴滚动练习
import numpy as np
num = np.arange(24).reshape(4,6)# 生成一个4行6列的二维数组
print("原数组：")
print(num)
print("对换数组：")
print(np.transpose(num))# 转置
print("转置数组：")
print(num.T)# 轴滚动

原数组：
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
对换数组：
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]
转置数组：
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]


In [3]:
num = np.arange(24).reshape(4,6)
re = num.swapaxes(0,1)#交换数组的两个轴
print("原数组：")
print(num)
print("调用swapaxes函数交换数组的两个轴：")
print(re)

原数组：
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
调用swapaxes函数交换数组的两个轴：
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]
